const QUOTES = [
  { id: 1, quote: "Je suis le Prince de tous les Saiyans. Personne ne me dépasse en puissance ou en orgueil.", character: "Vegeta" },
  { id: 2, quote: "La perfection... voilà ce que je suis. La créature ultime issue du génie du Dr Gero.", character: "Cell" },
  { id: 3, quote: "Gohan, tu dois vivre. Reste en vie... pour moi.", character: "Piccolo" },
  { id: 4, quote: "Tant qu'il existe des guerriers plus forts que moi dans l'univers, je continuerai à me surpasser !", character: "Goku" },
  { id: 5, quote: "Je règne depuis plus d'un million d'années. Aucun être dans cet univers ne m'est supérieur.", character: "Freezer" },
  { id: 6, quote: "Buu va tuer ! Buu va tout écraser ! Tout le monde mourra !", character: "Buu (Innocent)" },
  { id: 7, quote: "Cette rage en moi... je ne peux plus la retenir. Vous avez réveillé quelque chose d'effrayant.", character: "Gohan" },
  { id: 8, quote: "Même si je ne suis pas le plus fort, je resterai toujours là pour protéger ceux que j'aime.", character: "Krillin" },
  { id: 9, quote: "Dans mon époque, les Androïdes ont tout anéanti. Je suis venu pour qu'il n'en soit pas ainsi.", character: "Trunks (futur)" },
  { id: 10, quote: "Vous osez me réveiller pour si peu ? Toute cette galaxie méritera d'être détruite.", character: "Beerus" },
  { id: 11, quote: "Oh là là... quel dégât. Voulez-vous que nous recommencions depuis le début ?", character: "Whis" },
  { id: 12, quote: "Les mortels sont une erreur. Une imperfection que les dieux auraient dû corriger depuis longtemps.", character: "Zamasu" },
  { id: 13, quote: "Je ne me bats pas pour l'Empire. Je me bats pour pouvoir revoir le visage de mon fils.", character: "Bardock" },
  { id: 14, quote: "Je ne désire pas combattre. Mon seul souhait est de préserver chaque forme de vie qui existe.", character: "Androïde 16" },
  { id: 15, quote: "Tu es un Saiyan ! Un guerrier de l'élite ! Pas un gardien de planètes insignifiantes !", character: "Raditz" },
  { id: 16, quote: "Je ne suis pas une machine sans âme. J'ai des émotions, et je fais ce que je veux.", character: "Androïde 18" },
  { id: 17, quote: "La force transcende tout — la justice, l'amitié, les rêves. Il n'y a que la puissance.", character: "Jiren" },
  { id: 18, quote: "Je suis venu purifier cet univers souillé par les mortels, au nom d'une justice que les dieux ont abandonnée.", character: "Goku Black" },
  { id: 19, quote: "Même sans ki surhumain, je ne reculerai jamais. La volonté, c'est la seule force qui vaille.", character: "Tenshinhan" },
  { id: 20, quote: "Je suis le loup du désert ! Ne vous fiez pas à mon apparence — je suis un guerrier redoutable !", character: "Yamcha" },
  { id: 21, quote: "Kakarot... tu es le seul adversaire que j'aie jamais respecté. Je suis... fier de t'avoir connu.", character: "Vegeta" },
  { id: 22, quote: "C'est moi la fille du champion du monde ! Je suis tout à fait capable de me défendre seule, merci !", character: "Videl" },
  { id: 23, quote: "La destruction n'est pas qu'un devoir, parfois c'est aussi un plaisir. Mais chut, entre nous.", character: "Beerus" },
  { id: 24, quote: "Mes créations sont irréprochables. Vous, les humains, n'êtes que des matériaux pour parfaire mon œuvre.", character: "Androïde 20 (Dr Gero)" },
  { id: 25, quote: "Je suis le Super Saiyan Légendaire. Et toi, tu vas expier tous mes tourments.", character: "Broly (Légendaire)" },
];
